# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  newcontainerazuredemo:
    image: newcontainerazuredemo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
  db:
      image: mcr.microsoft.com/mssql/server:latest
      environment:
        SA_PASSWORD: bibiga73S!   # Set your desired SQL Server SA password
        ACCEPT_EULA: Y                   # Accept the SQL Server EULA
      ports:
        - 1435:1433                      # Port mapping for accessing the database server
      